import os
from PIL import Image, ImageDraw

def create_sprite_from_ascii(ascii_art, palette, size=(32, 32)):
    img = Image.new("RGBA", size, (0, 0, 0, 0))
    pixels = img.load()
    
    # Trim lines and filter
    lines = [line.strip() for line in ascii_art.split('\n') if line.strip()]
    
    for y, line in enumerate(lines[:size[1]]):
        for x, char in enumerate(line[:size[0]]):
            if char in palette:
                pixels[x, y] = palette[char]
    return img

def main():
    sprites_dir = r"C:\Users\User\Documents\Obsidian\Siesta\01_Projects\Game Dev Prototypes\FanIsle\assets\sprites"
    os.makedirs(sprites_dir, exist_ok=True)
    
    # Palette definition matching GBA style
    PALETTE = {
        '.': (0, 0, 0, 0),        # Transparent
        'k': (0, 0, 0, 255),      # Black outline
        'w': (255, 255, 255, 255),# White
        'g': (132, 216, 84, 255), # Light Green
        'G': (69, 160, 52, 255),  # Dark Green
        'b': (120, 180, 224, 255),# Light Blue
        'B': (60, 124, 176, 255), # Dark Blue
        'r': (224, 40, 56, 255),  # Red
        'R': (160, 20, 30, 255),  # Dark Red
        'y': (255, 208, 24, 255), # Yellow
        'p': (255, 152, 184, 255),# Pink
        'o': (224, 104, 32, 255), # Orange
        'O': (160, 64, 24, 255),  # Dark Orange
        'd': (180, 180, 180, 255),# Light Grey
        'D': (90, 90, 95, 255),   # Dark Grey
        'e': (180, 120, 70, 255), # Light Brown
        'E': (110, 60, 30, 255),  # Dark Brown
        'm': (120, 60, 140, 255), # Purple
        'M': (80, 30, 100, 255),  # Dark Purple
    }

    # 1. GENERATE CHARACTERS (256x256 sheet)
    char_sheet = Image.new("RGBA", (256, 256), (0, 0, 0, 0))
    
    # Simple templates for character shapes
    # Alligator Hero down walk frame 1
    hero_down_1 = """
    ................................
    ...........kkkkkkkkk............
    ..........kkgggggggkk...........
    .........kgggggggggggk..........
    .........kggkkkkkkkkggk.........
    ........kggkwwkggkwwkggk........
    ........kggkkkkggkkkkggk........
    ........kggggggggggggggk........
    ........kggggggggggggggk........
    .........kggggggggggggk.........
    ..........kkkkkkkkkkkk..........
    ...........krrrrrrrk............
    ..........krrrrrrrrrk...........
    ..........krrrrrrrrrk...........
    ..........krrrrrrrrrk...........
    ..........krrrrrrrrrk...........
    ..........krrrrrrrrrk...........
    ..........krrrrrrrrrk...........
    ..........krrrrrrrrrk...........
    ..........krrrkrrrkrrk..........
    ..........krrk.krrk.krk.........
    ...........kk...kk...kk.........
    ...........kgk..kgk.............
    ..........kggk.kggk.............
    ..........kkkk.kkkk.............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """
    
    # Alligator Hero down walk frame 2 (swapped feet)
    hero_down_2 = hero_down_1 # fallback simplicity
    
    # Hero up frame (back view)
    hero_up = """
    ................................
    ...........kkkkkkkkk............
    ..........kkgggggggkk...........
    .........kgggggggggggk..........
    .........kgggggggggggk..........
    .........kgggggggggggk..........
    .........kgggggggggggk..........
    .........kgggggggggggk..........
    .........kgggggggggggk..........
    .........kgggggggggggk..........
    ..........kkkkkkkkkkkk..........
    ...........krrrrrrrk............
    ..........krrrrrrrrrk...........
    ..........krrrrrrrrrk...........
    ..........krrrrrrrrrk...........
    ..........krrrrrrrrrk...........
    ..........krrrrrrrrrk...........
    ..........krrrrrrrrrk...........
    ..........krrrrrrrrrk...........
    ..........krrrrrrrrrk...........
    ..........krrk...krrk...........
    ...........kk.....kk............
    ...........kgk...kgk............
    ..........kggk...kggk...........
    ..........kkkk...kkkk...........
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """
    
    # Hero side frame (left/right)
    hero_side = """
    ................................
    ............kkkkkkkk............
    ...........kkggggggkk...........
    ..........kgggggggggk...........
    ..........kggkkkkkggk...........
    .........kggkwwkkwwgk...........
    .........kggkkkkkkkkk...........
    .........kggggggggggk...........
    .........kggggggggggk...........
    ..........kggggggggk............
    ...........kkkkkkkk.............
    ............krrrrrk.............
    ...........krrrrrrrk............
    ...........krrrrrrrk............
    ..........krrrrrrrrrk...........
    ..........krrrrrrrrrk...kkk.....
    ..........krrrrrrrrrk..kgggk....
    ..........krrrrrrrrrkkkggggk....
    ..........krrrrrrrrrkkggggk.....
    ..........krrrrrrrrrkkggkk......
    ..........krrk.krrk..kkk........
    ...........kk...kk..............
    ...........kgk..kgk.............
    ..........kggk.kggk.............
    ..........kkkk.kkkk.............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    # Goblins
    goblin_down = """
    ................................
    ...........kkkkkkkk.............
    .........kkkggggggkkk...........
    ........kggggggggggggk..........
    .......kggggkkkkkkggggk.........
    .......kgggkwwkggkwwkgk.........
    .......kgggkkkkggkkkkgk.........
    .......kggggggggggggggk.........
    ........kggggggggggggk..........
    .........kkkkkkkkkkkk...........
    ...........keeeeeee............
    ..........keeeeeeeeek...........
    ..........keeeeeeeeek...........
    ..........keeeeeeeeek...........
    ..........keeeeeeeeek...........
    ..........keeeeeeeeek...........
    ..........keeeeeeeeek...........
    ...........keeeeeee............
    ...........kgk...kgk............
    ..........kggk...kggk...........
    ..........kkkk...kkkk...........
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    # Skeleton
    skeleton = """
    ................................
    ...........kkkkkkkk.............
    ..........kwwwwwwwwk............
    .........kwwwwwwwwwwk...........
    .........kwwkkwwkkwwk...........
    .........kwwkkwwkkwwk...........
    .........kwwwwwwwwwwk...........
    .........kwwwwwwwwwwk...........
    ..........kwwkwwkwwk............
    ...........kkkkkkkk.............
    ............kwwk................
    ...........kwwwwk...............
    ..........kwwkwwk...............
    .........kwwk.kwwk..............
    ........kwwk...kwwk.............
    ........kkk.....kkk.............
    ........kwwk...kwwk.............
    ........kwwk...kwwk.............
    ........kkkk...kkkk.............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    # Bat
    bat_1 = """
    ................................
    ................................
    ..........kkkk...kkkk...........
    .........kmmmmk.kmmmmk..........
    ........kmmmmmmkmmmmmmk.........
    .......kmmmmmmmmmmmmmmmk........
    .......kmmmkkmmmmmmmkkmmk.......
    ......kmmmmwkkmmmmmwkkmmmk......
    ......kmmmmmkkmmmmmkkmmmmk......
    ......kmmmmmmmmmmmmmmmmmmk......
    .......kmmmmmmmmmmmmmmmmk.......
    ........kmmmmmmmmmmmmmmk........
    .........kmmmmmmmmmmmmk.........
    ..........kkmmmmmmmmkk..........
    ............kkkkkkkk............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """
    bat_2 = bat_1 # wings flaps simplified

    # Orc Scout
    orc = """
    ................................
    ...........kkkkkkkk.............
    ..........kkGGGGGGkk............
    .........kGGGGGGGGGGk...........
    .........kGGkwwGGkwwGk..........
    .........kGGkkkkGkkkkGk.........
    .........kGGGGGGGGGGGk..........
    .........kGGwGGGGGwGGk..........
    ..........kGGwwwwwGGk...........
    ...........kkGGGGGkk............
    ............kEEEEk..............
    ...........kEEEEEEk.............
    ..........kEEEEEEEEk............
    ..........kEEEEEEEEk............
    ..........kEEEEEEEEk............
    ..........kEEEEEEEEk............
    ..........kEEEEEEEEk............
    ...........kEEEEEEk.............
    ...........kGGk.kGGk............
    ..........kGGk...kGGk...........
    ..........kkkk...kkkk...........
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    # Night Lich
    lich = """
    ................................
    ...........kkkkkkkk.............
    ..........kyyyyyyyyk............
    .........kyyyyyyyyyyk...........
    .........kyykkkkyykkk...........
    .........kyykwwkyykww...........
    .........kyykkkkyykkk...........
    .........kBBBBBBBBBBk...........
    ........kBBBBBBBBBBBBk..........
    ........kBBkBBBBBBkBBk..........
    ........kBBkBBBBBBkBBk..........
    ........kBBkBBBBBBkBBk..........
    ........kBBBBBBBBBBBBk..........
    ........kBBBBBBBBBBBBk..........
    ........kBBBBBBBBBBBBk..........
    ........kBBBBBBBBBBBBk..........
    .........kBBBBBBBBBBk...........
    ..........kBBBBBBBBk............
    ...........kBBBBBBk.............
    ............kkkkkk..............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    # Vampire
    vampire = """
    ................................
    ...........kkkkkkkk.............
    ..........kwwwwwwwwk............
    .........kwwwwwwwwwwk...........
    .........kwwkkwwkkwwk...........
    .........kwwrwwkwwrww...........
    .........kwwwwwwwwwwk...........
    .........kwwkwwwwkwwk...........
    ..........kwwwwwwwwk............
    .........kkRRRRRRRRkk...........
    ........kRRRRRRRRRRRRk..........
    .......kRRRkkkkkkkkRRRk.........
    .......kRRk.kkkkkk.kRRk.........
    .......kRk..kkkkkk..kRk.........
    .......kk...kkkkkk...kk.........
    ............kkkkkk..............
    ............kwwkwwk.............
    ............kwwkwwk.............
    ............kkkkkkk.............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    # Golem
    golem = """
    ................................
    ..........kkkkkkkkkk............
    .........kDDDDDDDDDDk...........
    ........kDDDDDDDDDDDDk..........
    ........kDDkkDDDDkkDDk..........
    ........kDDwwDDDDwwDDk..........
    ........kDDkkDDDDkkDDk..........
    ........kDDDDDDDDDDDDk..........
    ........kDDGGGGGGGGDDk..........
    ........kDDGGGGGGGGDDk..........
    .........kDDDDDDDDDDk...........
    ........kkDDDDDDDDDDkk..........
    .......kDDDDDDDDDDDDDDk.........
    .......kDDDDDDDDDDDDDDk.........
    .......kDDDDDDDDDDDDDDk.........
    .......kDDDDDDDDDDDDDDk.........
    .......kDDDDDDDDDDDDDDk.........
    ........kDDDDDDDDDDDDk..........
    ........kDDk......kDDk..........
    ........kDDk......kDDk..........
    ........kkk........kkk..........
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    # Elder Mira
    mira = """
    ................................
    ...........kkkkkkkk.............
    ..........kwwwwwwwwk............
    .........kwwwwwwwwwwk...........
    .........kwwkkwwkkwwk...........
    .........kwwkkwwkkwwk...........
    .........kwwwwwwwwwwk...........
    .........kwwwwwwwwwwk...........
    .........kwwwwwwwwwwk...........
    ..........kwwwwwwwwk............
    ...........kBBBBBBk.............
    ..........kBBBBBBBBk............
    .........kBBBBBBBBBBk...........
    .........kBBBBBBBBBBk...........
    .........kBBBBBBBBBBk...........
    .........kBBBBBBBBBBk...........
    .........kBBBBBBBBBBk...........
    ..........kBBBBBBBBk............
    ..........kee....kee............
    ..........kee....kee............
    ..........kkk....kkk............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    # Healer
    healer = """
    ................................
    ...........kkkkkkkk.............
    ..........krrrrrrrrk............
    .........krrrrrrrrrrk...........
    .........krrkkwwkkwwk...........
    .........krrkkwwkkwwk...........
    .........krrrrrrrrrrk...........
    .........krrrrrrrrrrk...........
    ..........krrrrrrrrk............
    ...........kwwwwwwk.............
    ..........kwwrwwrwwk............
    .........kwwrrrrrrwwk...........
    .........kwwrrrrrrwwk...........
    .........kwwrwwrwwrww...........
    .........kwwrwwrwwrww...........
    .........kwwrwwrwwrww...........
    .........kwwrwwrwwrww...........
    ..........kwwwwwwkk.............
    ..........kee...kee.............
    ..........kee...kee.............
    ..........kkk...kkk.............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    # Blacksmith
    blacksmith = """
    ................................
    ...........kkkkkkkk.............
    ..........keeeeeeeek............
    .........keeeeeeeeeek...........
    .........keekkkkwwkkk...........
    .........keekwwkwwkww...........
    .........keekkkkkkkkk...........
    .........keeeeeeeeeek...........
    ..........keeeeeeeek............
    ...........kOOOOOOk.............
    ..........kOOOOOOOOk............
    .........kOOOOOOOOOOk...........
    .........kOOOOOOOOOOk...........
    .........kOOOOOOOOOOk...........
    .........kOOOOOOOOOOk...........
    .........kOOOOOOOOOOk...........
    .........kOOOOOOOOOOk...........
    ..........kOOOOOOk..............
    ..........kee..kee..............
    ..........kee..kee..............
    ..........kkk..kkk..............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    # Draw player walking directions
    # Cols 0-1: Down, 2-3: Up, 4-5: Left, 6-7: Right
    # Left and right will just mirror or draw side view
    hero_side_left = hero_side
    # We can mirror hero_side for right
    hero_side_right = ""
    for line in hero_side.strip().split('\n'):
        hero_side_right += line[::-1] + "\n"

    # Put on sheet
    # Row 0: Player
    char_sheet.paste(create_sprite_from_ascii(hero_down_1, PALETTE), (0, 0))
    char_sheet.paste(create_sprite_from_ascii(hero_down_2, PALETTE), (32, 0))
    char_sheet.paste(create_sprite_from_ascii(hero_up, PALETTE), (64, 0))
    char_sheet.paste(create_sprite_from_ascii(hero_up, PALETTE), (96, 0))
    char_sheet.paste(create_sprite_from_ascii(hero_side_left, PALETTE), (128, 0))
    char_sheet.paste(create_sprite_from_ascii(hero_side_left, PALETTE), (160, 0))
    char_sheet.paste(create_sprite_from_ascii(hero_side_right, PALETTE), (192, 0))
    char_sheet.paste(create_sprite_from_ascii(hero_side_right, PALETTE), (224, 0))
    
    # Row 1: Goblin
    char_sheet.paste(create_sprite_from_ascii(goblin_down, PALETTE), (0, 32))
    char_sheet.paste(create_sprite_from_ascii(goblin_down, PALETTE), (32, 32))
    char_sheet.paste(create_sprite_from_ascii(goblin_down, PALETTE), (64, 32)) # Back view placeholder
    char_sheet.paste(create_sprite_from_ascii(goblin_down, PALETTE), (96, 32))
    char_sheet.paste(create_sprite_from_ascii(goblin_down, PALETTE), (128, 32)) # Left side placeholder
    char_sheet.paste(create_sprite_from_ascii(goblin_down, PALETTE), (160, 32))
    char_sheet.paste(create_sprite_from_ascii(goblin_down, PALETTE), (192, 32)) # Right side placeholder
    char_sheet.paste(create_sprite_from_ascii(goblin_down, PALETTE), (224, 32))
    
    # Row 2: Enemies: Skeleton, Bat, Orc, Lich
    char_sheet.paste(create_sprite_from_ascii(skeleton, PALETTE), (0, 64))
    char_sheet.paste(create_sprite_from_ascii(skeleton, PALETTE), (32, 64))
    char_sheet.paste(create_sprite_from_ascii(bat_1, PALETTE), (64, 64))
    char_sheet.paste(create_sprite_from_ascii(bat_2, PALETTE), (96, 64))
    char_sheet.paste(create_sprite_from_ascii(orc, PALETTE), (128, 64))
    char_sheet.paste(create_sprite_from_ascii(orc, PALETTE), (160, 64))
    char_sheet.paste(create_sprite_from_ascii(lich, PALETTE), (192, 64))
    char_sheet.paste(create_sprite_from_ascii(lich, PALETTE), (224, 64))
    
    # Row 3: Vampire, Golem, Elder Mira, Healer Elenia
    char_sheet.paste(create_sprite_from_ascii(vampire, PALETTE), (0, 96))
    char_sheet.paste(create_sprite_from_ascii(vampire, PALETTE), (32, 96))
    char_sheet.paste(create_sprite_from_ascii(golem, PALETTE), (64, 96))
    char_sheet.paste(create_sprite_from_ascii(golem, PALETTE), (96, 96))
    char_sheet.paste(create_sprite_from_ascii(mira, PALETTE), (128, 96))
    char_sheet.paste(create_sprite_from_ascii(mira, PALETTE), (160, 96))
    char_sheet.paste(create_sprite_from_ascii(healer, PALETTE), (192, 96))
    char_sheet.paste(create_sprite_from_ascii(healer, PALETTE), (224, 96))
    
    # Row 4: Blacksmith Hektor
    char_sheet.paste(create_sprite_from_ascii(blacksmith, PALETTE), (0, 128))
    char_sheet.paste(create_sprite_from_ascii(blacksmith, PALETTE), (32, 128))

    # Save characters sheet
    char_sheet.save(os.path.join(sprites_dir, "characters.png"))
    print("Saved characters.png")


    # 2. GENERATE TILESET (128x128)
    tileset = Image.new("RGBA", (128, 128), (0, 0, 0, 0))
    
    # Grass tile
    grass_tile = """
    gggggggggggggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    gggggggggGgggggggggggggggggggggg
    ggggggggGGgggggggggggggggggggggg
    gggggggggGgggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    ggggggggggggggggggggggggGggggggg
    gggggggggggggggggggggggGGggggggg
    ggggggggggggggggggggggggGggggggg
    gggggggggggggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    gggggGgggggggggggggggggggggggggg
    ggggGGgggggggggggggggggggggggggg
    gggggGgggggggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    gggggggggggggggggggggggggggggggg
    """
    
    # Cave Floor
    cave_tile = """
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
    """
    # Let's add borders to cave tile
    lines = [list(line) for line in cave_tile.strip().split('\n')]
    for y in range(32):
        for x in range(32):
            if x == 0 or x == 31 or y == 0 or y == 31:
                lines[y][x] = 'D' # highlight outline
    cave_tile = "\n".join("".join(l) for l in lines)

    # Desert sand tile
    desert_tile = """
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    """
    # Dune ripples
    lines = [list(line) for line in desert_tile.strip().split('\n')]
    for i in range(5):
        dy = i * 6 + 4
        for dx in range(10):
            lines[dy][dx + 5] = 'o'
    desert_tile = "\n".join("".join(l) for l in lines)

    tileset.paste(create_sprite_from_ascii(grass_tile, PALETTE), (0, 0))
    tileset.paste(create_sprite_from_ascii(cave_tile, PALETTE), (32, 0))
    tileset.paste(create_sprite_from_ascii(desert_tile, PALETTE), (64, 0))
    
    tileset.save(os.path.join(sprites_dir, "tileset.png"))
    print("Saved tileset.png")


    # 3. GENERATE OBJECTS (128x128)
    objects = Image.new("RGBA", (128, 128), (0, 0, 0, 0))
    
    # Tree
    tree_sprite = """
    .............kkkkkk.............
    ...........kkggggggkk...........
    ..........kggggggggggk..........
    .........kggggggggggggk.........
    ........kggggggggggggggk........
    ........kggkkkkkkkkkkggk........
    ........kggk        kggk........
    ........kggk        kggk........
    ........kggkkkkkkkkkkggk........
    .........kggggggggggggk.........
    ..........kkggggggggkk..........
    ............kkkkkkkk............
    ..............kEEk..............
    ..............kEEk..............
    ..............kEEk..............
    ..............kEEk..............
    ..............kEEk..............
    ..............kEEk..............
    ..............kEEk..............
    ............kkEEEEkk............
    ...........kEEEEEEEEk...........
    ...........kkkkkkkkkk...........
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """
    # Replace space with light green
    tree_sprite = tree_sprite.replace(' ', 'g')

    # Rock
    rock_sprite = """
    ................................
    .............kkkkkkkk...........
    ...........kkDDDDDDDDkk.........
    ..........kDDDDDDDDDDDDk........
    ........kkDDDDDDDDDDDDDDkk......
    .......kDDDDDDDDDDDDDDDDDDk.....
    ......kDDDDDDDDDDDDDDDDDDDDk....
    .....kDDDDDDDDDDDDDDDDDDDDDDk...
    .....kDDDDDDDDDDDDDDDDDDDDDDk...
    ....kDDDDDDDDDDDDDDDDDDDDDDDDk..
    ....kDDDDDDDDDDDDDDDDDDDDDDDDk..
    ....kDDDDDDDDDDDDDDDDDDDDDDDDk..
    ....kDDDDDDDDDDDDDDDDDDDDDDDDk..
    ....kDDDDDDDDDDDDDDDDDDDDDDDDk..
    ....kDDDDDDDDDDDDDDDDDDDDDDDDk..
    ....kkkDDDDDDDDDDDDDDDDDDDDkkk..
    ......kkkkkkkkkkkkkkkkkkkkkk....
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    # Shrub
    shrub_sprite = """
    ................................
    ...........kkkkkkkk.............
    .........kkggggggggkk...........
    ........kggggggggggggk..........
    .......kggggggggggggggk.........
    ......kggggggggggggggggk........
    ......kggggrrggggggrrggk........
    ......kggggrrggggggrrggk........
    ......kggggggggggggggggk........
    ......kggggggggggggggggk........
    ......kggggggrrggggggggk........
    ......kggggggrrggggggggk........
    .......kggggggggggggggk.........
    ........kkggggggggggkk..........
    ..........kkkkkkkkkk............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    # Flint cluster
    flint_cluster = """
    ................................
    .............kkkk...............
    ............kDDDDk..............
    ...........kDDDDDDk.............
    ..........kDDDDDDDDk............
    ..........kDDDDDDDDk............
    ...........kDDDDDDk.............
    ............kkkkkk............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    # Campfire
    campfire = """
    ................................
    ...............kk...............
    ..............kyyk..............
    .............kyyyyk.............
    ............kyyyyyyk............
    ............koyyyyok............
    ...........koyyyyyyok...........
    ..........koooyyyyoook..........
    ..........koooyyyyoook..........
    .........kooooooooooook.........
    .........kkkoooooookkk..........
    ............kEEkEEk.............
    ...........kEEEEEEk.............
    ..........kEEEEEEEEk............
    ..........kkkkkkkkkk............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    # Chest
    chest = """
    ................................
    .........kkkkkkkkkkkkkk.........
    ........kEEEEEEEEEEEEEEk........
    .......kEEEEEEEEEEEEEEEEk.......
    ......kEEkkkkkkkkkkkkkkEEk......
    ......kEEk            kEEk......
    ......kEEk            kEEk......
    ......kEEkkkkkkkkkkkkkkEEk......
    ......kEEEEEEEEEEEEEEEEEEk......
    ......kEEEEEEEEEEEEEEEEEEk......
    ......kEEEEEEEEEEEEEEEEEEk......
    ......kEEEEEEEEEEEEEEEEEEk......
    ......kEEEEEEEEEEEEEEEEEEk......
    ......kEEEEEEEEEEEEEEEEEEk......
    ......kkkkkkkkkkkkkkkkkkkk......
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """
    chest = chest.replace(' ', 'E')

    # Bed
    bed = """
    ................................
    ................................
    ......kkkkkkkkkkkkkkkkkkkk......
    .....kwwwwwwwwwwwwwwwwwwwwk.....
    ....kwwwwwwwwwwwwwwwwwwwwwwk....
    ...kwwkkkkkkkkkkkkkkkkkkkkwwk...
    ...kwwkmmmmmmmmmmmmmmmmmmkwwk...
    ...kwwkmmmmmmmmmmmmmmmmmmkwwk...
    ...kwwkmmmmmmmmmmmmmmmmmmkwwk...
    ...kwwkmmmmmmmmmmmmmmmmmmkwwk...
    ...kwwkmmmmmmmmmmmmmmmmmmkwwk...
    ...kwwkmmmmmmmmmmmmmmmmmmkwwk...
    ...kwwkmmmmmmmmmmmmmmmmmmkwwk...
    ...kwwkkkkkkkkkkkkkkkkkkkkwwk...
    ....kwwwwwwwwwwwwwwwwwwwwwwk....
    .....kkkkkkkkkkkkkkkkkkkkkk.....
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    # Torch
    torch = """
    ................................
    ...............kk...............
    ..............kyyk..............
    .............kyyyyk.............
    .............koyyok.............
    ..............koook.............
    ...............kkk..............
    ...............kEk..............
    ...............kEk..............
    ...............kEk..............
    ...............kEk..............
    ...............kEk..............
    ...............kEk..............
    ...............kkk..............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    # Walls
    wood_wall = """
    ................................
    .........kkkkkkkkkkkkkk.........
    ........kEEEEEEEEEEEEEEk........
    .......kEEEEEEEEEEEEEEEEk.......
    ......kEEEEEEEEEEEEEEEEEEk......
    ......kEEkkkkkkkkkkkkkkEEk......
    ......kEEk            kEEk......
    ......kEEk            kEEk......
    ......kEEkkkkkkkkkkkkkkEEk......
    ......kEEEEEEEEEEEEEEEEEEk......
    ......kEEEEEEEEEEEEEEEEEEk......
    ......kEEEEEEEEEEEEEEEEEEk......
    ......kEEEEEEEEEEEEEEEEEEk......
    ......kEEEEEEEEEEEEEEEEEEk......
    ......kkkkkkkkkkkkkkkkkkkk......
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """
    wood_wall = wood_wall.replace(' ', 'e')

    stone_wall = """
    ................................
    .........kkkkkkkkkkkkkk.........
    ........kDDDDDDDDDDDDDDk........
    .......kDDDDDDDDDDDDDDDDk.......
    ......kDDDDDDDDDDDDDDDDDDk......
    ......kDDkkkkkkkkkkkkkkDDk......
    ......kDDk            kDDk......
    ......kDDk            kDDk......
    ......kDDkkkkkkkkkkkkkkDDk......
    ......kDDDDDDDDDDDDDDDDDDk......
    ......kDDDDDDDDDDDDDDDDDDk......
    ......kDDDDDDDDDDDDDDDDDDk......
    ......kDDDDDDDDDDDDDDDDDDk......
    ......kDDDDDDDDDDDDDDDDDDk......
    ......kkkkkkkkkkkkkkkkkkkk......
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """
    stone_wall = stone_wall.replace(' ', 'd')

    objects.paste(create_sprite_from_ascii(tree_sprite, PALETTE), (0, 0))
    objects.paste(create_sprite_from_ascii(rock_sprite, PALETTE), (32, 0))
    objects.paste(create_sprite_from_ascii(shrub_sprite, PALETTE), (64, 0))
    objects.paste(create_sprite_from_ascii(flint_cluster, PALETTE), (96, 0))
    
    objects.paste(create_sprite_from_ascii(campfire, PALETTE), (0, 32))
    objects.paste(create_sprite_from_ascii(chest, PALETTE), (32, 32))
    objects.paste(create_sprite_from_ascii(bed, PALETTE), (64, 32))
    objects.paste(create_sprite_from_ascii(torch, PALETTE), (96, 32))
    
    objects.paste(create_sprite_from_ascii(wood_wall, PALETTE), (0, 64))
    objects.paste(create_sprite_from_ascii(stone_wall, PALETTE), (32, 64))
    
    objects.save(os.path.join(sprites_dir, "objects.png"))
    print("Saved objects.png")


    # 4. GENERATE ITEMS (128x128)
    items = Image.new("RGBA", (128, 128), (0, 0, 0, 0))
    
    # Wood icon
    wood_icon = """
    ................................
    ............kkkkkk..............
    ..........kkEEEEEEkk............
    .........kEEEEEEEEEEk...........
    ........kEEkkkkkkkkEEk..........
    ........kEEkkkkkkkkEEk..........
    .........kEEEEEEEEEEk...........
    ..........kkEEEEEEkk............
    ............kkkkkk..............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    # Stone icon
    stone_icon = """
    ................................
    ............kkkkkk..............
    ..........kkDDDDDDkk............
    .........kDDDDDDDDDDk...........
    ........kDDDDDDDDDDDDk..........
    ........kDDDDDDDDDDDDk..........
    .........kDDDDDDDDDDk...........
    ..........kkDDDDDDkk............
    ............kkkkkk..............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    # Flint icon
    flint_icon = """
    ................................
    .............kkkk...............
    ............kDDDDk..............
    ...........kDDDDDDk.............
    ..........kDDDDDDDDk............
    ..........kDDDDDDDDk............
    ...........kDDDDDDk.............
    ............kkkkkk............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    # Berries
    berries_icon = """
    ................................
    ............kkkkkk..............
    ..........kkrrrrrrkk............
    .........krrrrrrrrrrk...........
    ........krrrrrrrrrrrrk..........
    ........krrrrrrrrrrrrk..........
    .........krrrrrrrrrrk...........
    ..........kkrrrrrrkk............
    ............kkkkkk..............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    # Cooked Berries
    cooked_berries_icon = """
    ................................
    ............kkkkkk..............
    ..........kkooooookk............
    .........kooooooooook...........
    ........koooooooooooook.........
    ........koooooooooooook.........
    .........kooooooooook...........
    ..........kkooooookk............
    ............kkkkkk..............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    items.paste(create_sprite_from_ascii(wood_icon, PALETTE), (0, 0))
    items.paste(create_sprite_from_ascii(stone_icon, PALETTE), (32, 0))
    items.paste(create_sprite_from_ascii(flint_icon, PALETTE), (64, 0))
    items.paste(create_sprite_from_ascii(berries_icon, PALETTE), (96, 0))
    items.paste(create_sprite_from_ascii(cooked_berries_icon, PALETTE), (0, 32))
    
    items.save(os.path.join(sprites_dir, "items.png"))
    print("Saved items.png")


    # 5. GENERATE MINOR-SFX (128x128)
    minor_sfx = Image.new("RGBA", (128, 128), (0, 0, 0, 0))
    
    # Slash Frame 1
    slash_1 = """
    ................................
    ................................
    ......................kk........
    ....................kkwwk.......
    ..................kkwwkk........
    ................kkwwkk..........
    ..............kkwwkk............
    ............kkwwkk..............
    ..........kkwwkk................
    ........kkwwkk..................
    ......kkwwkk....................
    ....kkwwk.......................
    ..kkkk..........................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """
    
    # Sprint Dust Frame 1
    dust_1 = """
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ...................ww...........
    ..................wwww..........
    .................wwwwww.........
    ..................wwww..........
    ...................ww...........
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    """

    minor_sfx.paste(create_sprite_from_ascii(slash_1, PALETTE), (0, 0))
    minor_sfx.paste(create_sprite_from_ascii(dust_1, PALETTE), (0, 32))
    
    minor_sfx.save(os.path.join(sprites_dir, "minor-sfx.png"))
    print("Saved minor-sfx.png")
    print("All assets generated successfully!")

if __name__ == "__main__":
    main()
